version: 2
updates:
  - package-ecosystem: pip
    directory: /makervault/api
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /makervault/web
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /makervault/slicer-bridge
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /makervault/api
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /makervault/web
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
